using EC1.Lab.Pages.Product.Events;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace EC1.Lab.Pages.Product.Sub_Pages
{
    
    //Use RAzor to get th efunction of selected input
    public partial class GridViewControl : System.Web.UI.UserControl
    {

        public delegate void ChildControlDelegate(ProductSelectEventArgs args);
        public event ChildControlDelegate SelectionHandler;
        IAuthenticationManager authenticationManager; //= HttpContext.Current.GetOwinContext().Authentication;



    protected void Page_Load(object sender, EventArgs e)
        {
            authenticationManager = HttpContext.Current.GetOwinContext().Authentication;
            //return authenticationManager.User.IsInRole("Customer") ? "true" : "false";
            //dataProductsGrid.SelectedRow.Visible = false ;
            GridViewRow viewRow = dataProductsGrid.SelectedRow;
            if (authenticationManager.User.IsInRole("Customer"))
            {
                dataProductsGrid.Visible = false;
                dataProductsGrid.AutoGenerateSelectButton = true;
                this.dataProductsGrid.Columns[1].Visible = false;
                this.dataProductsGrid.Columns[3].Visible = false;
                this.dataProductsGrid.Columns[5].Visible = false;
            }
            else if (authenticationManager.User.IsInRole("Admin"))
            {
                dataProductsGrid.AutoGenerateEditButton = true;
                dataProductsGrid.AutoGenerateDeleteButton = true;
                //dataProductsGrid.FindControl("imgProduct").EnableViewState = false;
                //dataProductsGrid.TemplateField
            }
        }

        protected void OnSelectedIndexChanged(object sender, EventArgs e)
        {
            GridViewRow viewRow = dataProductsGrid.SelectedRow;            
            ProductSelectEventArgs pe = new ProductSelectEventArgs();
            pe.ProductId = viewRow.Cells[1].Text;
            pe.ProductName = viewRow.Cells[2].Text;
            pe.ProductDescription = viewRow.Cells[3].Text;
            pe.ProductPrice = viewRow.Cells[4].Text;

            if (SelectionHandler != null)
            {
                SelectionHandler(pe);
            }
        }

        protected void dataProductsGrid_RowDataBound(object sender, GridViewRowEventArgs e)
        {
            if (e.Row.RowType != DataControlRowType.DataRow) return;

            if (e.Row.RowType == DataControlRowType.DataRow || e.Row.RowType == DataControlRowType.Header)
            {
                if (authenticationManager.User.IsInRole("Admin"))
                {
                    //e.Row.FindControl("imgProduct").Visible = false;
                    //e.Row.Cells[9].Visible = false;
                    //e.Row.Cells[9].
                }

                //if (IsSelectable())
                //{

                //}
                //else
                //{
                //    Button btn = (Button)e.Row.FindControl("btnEdit");
                //    btn.Visible = false;
                //}

                //if (IsEditable())
                //{
                //    Button btnEdit = (Button)e.Row.FindControl("btnEdit");
                //    Button btnDelete = (Button)e.Row.FindControl("btnDelete");
                //    Button btnNew = (Button)e.Row.FindControl("btnNew");
                //    btnEdit.Visible = true;
                //    btnDelete.Visible = true;
                //    btnNew.Visible = true;
                //}
                //else
                //{
                //    Button btnEdit = (Button)e.Row.FindControl("btnEdit");
                //    Button btnDelete = (Button)e.Row.FindControl("btnDelete");
                //    Button btnNew = (Button)e.Row.FindControl("btnNew");
                //    btnEdit.Visible = false;
                //    btnDelete.Visible = false;
                //    btnNew.Visible = false;
                //}
            }
        }

        //public string IsSelectable()
        //{
        //    var authenticationManager = HttpContext.Current.GetOwinContext().Authentication;
        //    return authenticationManager.User.IsInRole("Customer") ? "true":"false";
        //}

        //public string IsEditable()
        //{
        //    var authenticationManager = HttpContext.Current.GetOwinContext().Authentication;
        //    return authenticationManager.User.IsInRole("Admin") ? "true" : "false";
        //}
    }
}