// <auto-generated />
namespace EC1.Lab.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Book5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Book5));
        
        string IMigrationMetadata.Id
        {
            get { return "201911212042508_Book5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
