using EC1.Lab.Domain;
using EC1.Lab.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace EC1.Lab.Pages.AdminStuff
{
    public partial class EditUser : System.Web.UI.Page
    {
        private List<AppUser> users;
        protected void Page_Load(object sender, EventArgs e)
        {
            var user = HttpContext.Current.User;
            Guid id = getUserId();
            users = new List<AppUser>();

            userGridView.AutoGenerateEditButton = true;
            userGridView.AutoGenerateDeleteButton = true;

            using (var context = new ApplicationDbContext())
            {
                users = context.Users.Where(c => c.Id != id.ToString()).ToList();
            }
        }

        public Guid getUserId()
        {
            var user = HttpContext.Current.User;
            Guid id = Guid.Parse(user.Identity.GetUserId());
            return id;
        }

        public void LoadUser()
        {
            using (var context = new ApplicationDbContext())
            {
                var user = HttpContext.Current.User;
                Guid id = Guid.Parse(user.Identity.GetUserId());
                users = context.Users.Where(c => c.Email == txtemail.Text || c.UserName == txtemail.Text).ToList();
                userGridView.DataSource = users;
                userGridView.DataBind();
            }
        }

        protected void btnSubmit_Click(object sender, EventArgs e)
        {
            LoadUser();
        }

        public void PendingRecordsGridview_RowDeleting(Object sender, GridViewDeleteEventArgs e)
        {
            
        }
    }
}